sudo: required

language: generic

services:
  - docker

before_install:
  - docker build -t nexus.yildiz-games.be/repository/docker-internal/test:latest .
script:
  - docker images nexus.yildiz-games.be/repository/docker-internal/test:latest
  
after_success:
  - docker push nexus.yildiz-games.be/repository/docker-internal/test:latest;
