sudo: required

language: generic

services:
  - docker

before_install:
  - docker build -t http://nexus.yildiz-games.be/repository/docker-internal/test:latest .
script:
  - docker images http://nexus.yildiz-games.be/repository/docker-internal/test:latest
  
after_success:
  - docker push http://nexus.yildiz-games.be/repository/docker-internal/test:latest;
